/**
 * Document service (Module 7). Pure business logic (no req/res).
 *
 * Documents are generated by rendering a template's content with supplied values
 * (reusing the pure engine from Module 6) and persisting the result together with
 * a snapshot of the source template. Every operation is confined to the actor's
 * organization (tenant isolation): a document — or a template/customer referenced
 * during generation — in another org is reported as "not found", never leaked.
 */
import Document from './document.model.js';
import Template from '../templates/template.model.js';
import Customer from '../customers/customer.model.js';
import { renderContent } from '../templates/template.engine.js';
import ApiError from '../../utils/ApiError.js';
import { orgScope, requireOrganization, listResources } from '../../utils/query.js';

/**
 * Load a document scoped to the actor's org, or throw 404. Shared by every
 * read/mutation path so isolation is enforced in one place.
 * @returns {Promise<import('mongoose').Document>}
 */
async function loadDocument(actor, id) {
  const document = await Document.findOne({ _id: id, ...orgScope(actor) });
  if (!document) {
    throw ApiError.notFound('Document not found', { code: 'DOCUMENT_NOT_FOUND' });
  }
  return document;
}

/** Load a template in the actor's org (source for generation), or throw 404. */
async function loadTemplate(actor, id) {
  const template = await Template.findOne({ _id: id, ...orgScope(actor) });
  if (!template) {
    throw ApiError.notFound('Template not found', { code: 'TEMPLATE_NOT_FOUND' });
  }
  return template;
}

/** Verify a customer belongs to the actor's org (optional link), or throw 404. */
async function assertCustomer(actor, id) {
  if (!id) return null;
  const customer = await Customer.findOne({ _id: id, ...orgScope(actor) }).select('_id');
  if (!customer) {
    throw ApiError.notFound('Customer not found', { code: 'CUSTOMER_NOT_FOUND' });
  }
  return customer._id;
}

/** Capture an immutable snapshot of a template at generation time. */
function snapshotOf(template) {
  return {
    name: template.name,
    type: template.type,
    content: template.content,
    variables: (template.variables ?? []).map((variable) => ({
      key: variable.key,
      label: variable.label ?? null,
      type: variable.type,
      required: !!variable.required,
      defaultValue: variable.defaultValue ?? null,
    })),
  };
}

/**
 * List documents with pagination, optional filtering (type/status/tag/template/
 * customer) and free-text search across the title. Scoped to the actor's org.
 * @param {object} actor
 * @param {{ page:number, limit:number, sort:string, q?:string, type?:string, status?:string, tag?:string, templateId?:string, customerId?:string }} query
 */
export async function listDocuments(
  actor,
  { page, limit, sort, q, type, status, tag, templateId, customerId }
) {
  return listResources(Document, 'documents', {
    actor,
    page,
    limit,
    sort,
    filters: { type, status, tags: tag, template: templateId, customer: customerId },
    q,
    searchFields: ['title'],
  });
}

/** A single document by id, scoped to the actor's org. */
export async function getDocumentById(actor, id) {
  const document = await loadDocument(actor, id);
  return document.toJSON();
}

/**
 * Generate a document from a template: render its content with the supplied
 * values, capture a snapshot of the template, and persist the result.
 * @param {object} actor
 * @param {{ templateId:string, title?:string, customerId?:string|null, status?:string, values?:object, tags?:string[] }} data
 */
export async function generateDocument(actor, data) {
  requireOrganization(actor, 'manage documents');

  const template = await loadTemplate(actor, data.templateId);
  const customerId = await assertCustomer(actor, data.customerId);

  const values = data.values ?? {};
  const rendered = renderContent(template.content, template.variables, values);

  const document = new Document({
    organization: actor.organization,
    title: data.title || template.name,
    type: template.type,
    status: data.status,
    template: template._id,
    templateSnapshot: snapshotOf(template),
    customer: customerId,
    values,
    content: rendered.content,
    missingRequired: rendered.missingRequired,
    tags: data.tags,
    createdBy: actor.id,
  });

  await document.save();
  return document.toJSON();
}

/**
 * Regenerate a document's content from its captured template snapshot using new
 * values. The snapshot (not the current template) is the source of truth, so the
 * document stays reproducible even if the template later changed.
 * @param {object} actor
 * @param {string} id
 * @param {object} values
 */
export async function regenerateDocument(actor, id, values = {}) {
  const document = await loadDocument(actor, id);
  const snapshot = document.templateSnapshot ?? {};
  const rendered = renderContent(snapshot.content ?? '', snapshot.variables ?? [], values);

  document.values = values;
  document.content = rendered.content;
  document.missingRequired = rendered.missingRequired;
  await document.save();
  return document.toJSON();
}

/** Update editable document fields (title/type/status/content/customer/tags). */
export async function updateDocument(actor, id, updates) {
  const document = await loadDocument(actor, id);

  const { customerId, ...rest } = updates;
  if (customerId !== undefined) {
    document.customer = await assertCustomer(actor, customerId);
  }
  Object.assign(document, rest);

  await document.save();
  return document.toJSON();
}

/** Permanently delete a document. */
export async function deleteDocument(actor, id) {
  const document = await loadDocument(actor, id);
  await document.deleteOne();
}
