/**
 * Pure HTML builder for PDF export (Module 8 — PDF Engine).
 *
 * Turns a generated document (the plain JSON shape returned by the document
 * service) into a self-contained, print-ready HTML page. This module performs no
 * I/O: it only produces strings, so it is fully unit-testable and reused by the
 * renderer, which converts the HTML to a PDF with a headless browser.
 */

/** HTML-escape a value so user content can't break out of the markup. */
export function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Derive a safe download filename from a document's title.
 * Falls back to `document.pdf` when the title has no usable characters.
 */
export function pdfFilename(document) {
  const base = String(document?.title ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return `${base || 'document'}.pdf`;
}

/** Format an ISO/date value as a human-readable date, or '' when absent. */
function formatDate(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

const PAGE_STYLES = `
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1a1a1a;
    font-size: 12px;
    line-height: 1.6;
    margin: 0;
  }
  .doc-header {
    border-bottom: 2px solid #111;
    padding-bottom: 12px;
    margin-bottom: 20px;
  }
  .doc-title { font-size: 22px; font-weight: 700; margin: 0 0 6px; }
  .doc-meta { color: #555; font-size: 11px; }
  .doc-meta span + span::before { content: "·"; margin: 0 6px; color: #bbb; }
  .doc-content {
    white-space: pre-wrap;
    word-wrap: break-word;
    font-size: 12.5px;
  }
  .doc-footer {
    margin-top: 28px;
    padding-top: 10px;
    border-top: 1px solid #ddd;
    color: #888;
    font-size: 10px;
  }
`;

/**
 * Build a complete HTML page for a document.
 * @param {object} document - plain document (title, type, status, content, …)
 * @returns {string} full HTML document
 */
export function buildDocumentHtml(document = {}) {
  const title = escapeHtml(document.title || 'Document');
  const type = document.type ? escapeHtml(document.type) : '';
  const status = document.status ? escapeHtml(document.status) : '';
  const templateName = document.templateSnapshot?.name
    ? escapeHtml(document.templateSnapshot.name)
    : '';
  const generatedOn = formatDate(document.createdAt);

  const metaParts = [];
  if (status) metaParts.push(`<span>${status}</span>`);
  if (type) metaParts.push(`<span>${type}</span>`);
  if (templateName) metaParts.push(`<span>from ${templateName}</span>`);
  if (generatedOn) metaParts.push(`<span>${generatedOn}</span>`);

  const content = escapeHtml(document.content || '');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${title}</title>
<style>${PAGE_STYLES}</style>
</head>
<body>
<header class="doc-header">
<h1 class="doc-title">${title}</h1>
<div class="doc-meta">${metaParts.join('')}</div>
</header>
<main class="doc-content">${content}</main>
<footer class="doc-footer">Generated by DocFlow AI${generatedOn ? ` · ${generatedOn}` : ''}</footer>
</body>
</html>`;
}
